name: Build Laravel Container

on:
  push:
    paths:
      - 'laravel/**'
  pull_request:
    branches:
      - '!dependabot/**'
  workflow_run:
    workflows:
      - Build PHP Vanity Tags
    branches: [ 'master', 'feature/**' ]
    types:
      - completed
  workflow_dispatch:

jobs:
  laravel-build:
    name: "Bake Laravel Container"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: laravel

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - uses: docker/build-push-action@v3
        name: Build & Push
        with:
          context: laravel
          platforms: ${{ !env.ACT && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          pull: true
          push: ${{ !env.ACT && true || false }}
          build-args: |
            PHP_VERSION=${{ matrix.version }}
          tags: |
            matthewbaggett/laravel:${{ matrix.version }}
          cache-from: ${{ !env.ACT && 'type=gha' || 'type=local,src=.github/cache/docker' }}
          cache-to: ${{ !env.ACT && 'type=gha,mode=max' || 'type=local,dest=.github/cache/docker' }}

  laravel-tag-latest:
    name: "Bake Laravel Container"
    runs-on: ubuntu-latest
    needs: [ laravel-build ]
    steps:
      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: "Retag matthewbaggett/laravel:${{ matrix.version }} to matthewbaggett/laravel:latest"
        if: ${{ !env.ACT }}
        run: | 
          docker pull matthewbaggett/laravel:8.2
          docker tag matthewbaggett/laravel:8.2 matthewbaggett/laravel:latest
          docker push matthewbaggett/laravel:latest
