name: Lint dockerfiles

on: [push]

jobs:
  lintDockerFiles:
    name: Lint docker files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lint docker files
        uses: docker://cdssnc/docker-lint