name: Build Octoprint

permissions:
  contents: read
  packages: write

on:
  workflow_call:
  workflow_dispatch:

env:
  should_push: ${{ github.ref == 'refs/heads/main' }}

jobs:
  octoprint-build:
    name: "Bake Octoprint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v3
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/build-push-action@v3
        name: Build Octoprint
        with:
          context: octoprint
          target: octoprint
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          pull: true
          push: ${{ env.should_push && !env.ACT }}
          tags: matthewbaggett/octoprint:latest

  octoprint-mjpg-build:
    name: "Bake Octoprint for yuvu cameras"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v3
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/build-push-action@v3
        name: Build Octoprint MJPG Streamer Variant
        with:
          context: octoprint
          target: octoprint-mjpg-streamer
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          pull: true
          push: ${{ env.should_push && !env.ACT }}
          tags: matthewbaggett/octoprint:mjpg-streamer-yu12
