name: Build PHP Vanity Tags

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Build PHP Flavours
    branches: [ 'master', 'feature/**' ]
    types:
      - completed

jobs:
  php-vanity-tags:
    name: Vanity Tags
    runs-on: ubuntu-latest
    env:
      latest-stable-version: "8.3"
      base_tag: "benzine/php"
    strategy:
      fail-fast: false
      matrix:
        variant:
          - cli
          - nginx
          - apache
        output_tag:
          - "benzine/php"
          - "gone/php"
          - "ghcr.io/benzine-framework/php"
    steps:
      - name: "Setup: Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: "Setup: Login to GHCR"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: "Retag ${{ env.base_tag }}:${{ matrix.variant }}-${{ env.latest-stable-version }} to ${{ matrix.output_tag }}:${{ matrix.variant }}"
        run: |
          docker pull ${{ env.base_tag }}:${{ matrix.variant }}-${{ env.latest-stable-version }}
          docker tag ${{ env.base_tag }}:${{ matrix.variant }}-${{ env.latest-stable-version }} ${{ matrix.output_tag }}:${{ matrix.variant }}
          docker push ${{ matrix.output_tag }}:${{ matrix.variant }}
          
