name: Build Redis

on:
  push:
    paths:
      - 'redis/**'
  pull_request:
    branches:
      - '!dependabot/**'
  workflow_run:
    workflows:
      - Lint Docker Files
    branches: [ 'master', 'feature/**' ]
    types:
      - completed
  workflow_dispatch:

jobs:
  redis-build:
    name: "Redis with Healthchecks"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix:
        redis:
          - 3
          - 4
          - 5
          - 6
          - 6-alpine
          - 6-buster
          - 6.0
          - 6.1
          - 6.2
          - 7
          - 7-alpine
          - 7-bookworm
          - 7.0
          - 7.1
          - 7.2
          - latest
    steps:
      - name: "Setup: Setup QEMU"
        uses: docker/setup-qemu-action@v2

      - name: "Setup: Expose GitHub Runtime"
        uses: crazy-max/ghaction-github-runtime@v3

      - name: "Setup: Setup Docker Buildx"
        uses: docker/setup-buildx-action@v2

      - name: "Setup: Checkout Source"
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            redis

      - name: "Setup: Login to Docker Hub"
        if: ${{ !env.ACT }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: "Setup: Login to GHCR"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: "Build: Build"
        uses: docker/build-push-action@v5
        with:
          context: redis
          build-contexts: |
            redis=docker-image://redis:${{ matrix.redis }}
          platforms: ${{ !env.ACT && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          pull: true
          push: ${{ !env.ACT && true || false }}
          tags: |
            ${{ !env.ACT && format('benzine/redis:{0}',matrix.redis) || '' }}
            ${{ format('ghcr.io/benzine-framework/redis:{0}', matrix.redis) }}
          cache-from: ${{ !env.ACT && 'type=gha' || 'type=local,src=.cache' }}
          cache-to: ${{ !env.ACT && 'type=gha,mode=max' || 'type=local,dest=.cache' }}


