name: Build Swarm Monitor

on:
  push:
    paths:
      - 'swarm-monitor/**'
  workflow_dispatch:

jobs:
  swarm-monitor-build:
    name: Build Swarm Monitor
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Bake
        working-directory: swarm-monitor
        run: docker buildx bake --push

