name: Build Wordpress Container

permissions:
  contents: read
  packages: write

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "wordpress/**"
      - ".github/workflows/wordpress.yml"

jobs:
  wordpress-build:
    name: "Bake Wordpress Container"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v2

      - name: "Setup: Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: matthewbaggett
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: "Setup: Login to GHCR"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: matthewbaggett
          password: ${{ secrets.GHCR_PASSWORD }}

      - uses: docker/build-push-action@v3
        name: Build & Push
        with:
          context: wordpress
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: |
            matthewbaggett/wordpress
          build-contexts: |
            php:nginx=docker-image://ghcr.io/benzine-framework/php:nginx-8.2
